---
- hosts: home
  become: yes
  become_method: sudo
  tasks:
    - name: Update everything
      dnf:
        name: "*"
        state: latest
    - name: Autoremove unneeded packages installed as dependencies
      dnf:
        autoremove: yes


